model_args:
  pretrained_model_name_or_path: "mistralai/Mixtral-8x7B-Instruct-v0.1"
  torch_dtype: bfloat16
  quant: true
tokenizer_args:
  pretrained_model_name_or_path: "mistralai/Mixtral-8x7B-Instruct-v0.1"
  padding_side: "left"
template_args:  # Used in creating prompts for the dataset. See src/data/utils.py#preprocess_chat_instance.
  apply_chat_template: False
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"